<x-layouts::app :title="__('New support request')">
    <div class="mx-auto max-w-3xl"><a href="{{ route('tickets.index') }}" class="text-sm font-semibold text-slate-500 hover:text-slate-900" wire:navigate>← Back to my requests</a><div class="mt-5"><p class="text-sm font-semibold text-indigo-600">WE’RE HERE TO HELP</p><h1 class="mt-2 text-3xl font-semibold tracking-tight">Tell us what’s going on.</h1><p class="mt-2 text-slate-500">Give us a little context so the right person can jump in.</p></div>
        <form method="POST" action="{{ route('tickets.store') }}" class="mt-7 space-y-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8">@csrf
            <div><label for="subject" class="mb-2 block text-sm font-semibold">Subject</label><input id="subject" name="subject" value="{{ old('subject') }}" required minlength="8" maxlength="160" placeholder="A short summary of the issue" class="w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring-indigo-500">@error('subject')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
            <div class="grid gap-5 sm:grid-cols-2"><div><label for="category_id" class="mb-2 block text-sm font-semibold">What do you need help with?</label><select id="category_id" name="category_id" required class="w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring-indigo-500"><option value="">Choose a category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id') == $category->id)>{{ $category->name }}</option>@endforeach</select>@error('category_id')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div><div><label for="priority" class="mb-2 block text-sm font-semibold">How urgent is it?</label><select id="priority" name="priority" required class="w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring-indigo-500">@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(old('priority', 'normal') === $priority->value)>{{ $priority->label() }}</option>@endforeach</select>@error('priority')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div></div>
            <div><label for="description" class="mb-2 block text-sm font-semibold">Details</label><textarea id="description" name="description" rows="7" required minlength="20" maxlength="10000" placeholder="What happened? What did you expect? Include any steps that might help us reproduce it." class="w-full rounded-xl border-slate-200 focus:border-indigo-500 focus:ring-indigo-500">{{ old('description') }}</textarea><p class="mt-2 text-xs text-slate-400">Please don’t include passwords or other sensitive information.</p>@error('description')<p class="mt-1 text-sm text-rose-600">{{ $message }}</p>@enderror</div>
            @if($errors->any())<p role="alert" class="rounded-xl bg-rose-50 px-4 py-3 text-sm text-rose-700">Please review the highlighted fields and try again.</p>@endif
            <div class="flex flex-col-reverse gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:justify-end"><a href="{{ route('tickets.index') }}" class="rounded-xl px-4 py-3 text-center text-sm font-semibold text-slate-600 hover:bg-slate-50" wire:navigate>Cancel</a><button class="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700">Submit request <span class="ml-1">→</span></button></div>
        </form>
    </div>
</x-layouts::app>